### ISSUE TITLE
ligatures in vscode

### ISSUE THREAD

**Issue by tobsn** [mietzen/juliamono-nerd-font#3] opened 2024-03-05 02:01 UTC
can't get them to work... any idea?

**Comment by mietzen** [comment] 2024-03-05 05:03
Can you please be more specific? Which ligatures are you missing?

![image](https://github.com/mietzen/juliamono-nerd-font/assets/31704359/15be98fa-af47-47b4-a24a-b5df77e629fe)

Or can't you get the font to work?

`'JuliaMono Nerd Font Mono'`
![image](https://github.com/mietzen/juliamono-nerd-font/assets/31704359/748705e5-67ee-4537-9c42-9926137a0d2e)

Also if you realy are missing ligatures I would suggest opening a ticket at https://github.com/cormullion/juliamono, I'm just the guy adding the Nerd part ;)

**Comment by mietzen** [comment] 2024-03-07 05:23
Any feedback @tobsn?

**Comment by tobsn** [comment] 2024-03-07 16:40
sorry, busy week - I meant double/triple equals for example.
=== ==! etc.

They seem to not work with the latin version at least (which, why does this look so much better? :))

**Comment by mietzen** [comment] 2024-03-07 16:47
> sorry, busy week - I meant double/triple equals for example. === ==! etc.
> 
> They seem to not work with the latin version at least (which, why does this look so much better? :))

Sorry I still don't get what you mean, could you give me the [Unicode](https://en.wikipedia.org/wiki/Unicode) code point, e.g. U+2261 and perhaps post a screenshot of the working ligature in another font vs. the non working in julia?

**Comment by tobsn** [comment] 2024-03-07 17:12
fira code:
![ZuCcvKOzrNFWWl3U9eiySvFKvLnBx0fu](https://github.com/mietzen/juliamono-nerd-font/assets/109529/00696ea0-10c0-4269-acca-6e5348d4e95d)
![fDoAvbGgxet4Y1beOpzgdun9CZtqmZMQ](https://github.com/mietzen/juliamono-nerd-font/assets/109529/7ae66a65-efc3-4614-84e3-6f0112354520)

JuliaMonoLatin Nerd Font Mono:
![eWw1Z6GE0MrEtfB4TIq1of1P5fsMLPlf](https://github.com/mietzen/juliamono-nerd-font/assets/109529/6ae82fb5-5ce0-4397-929f-1c9ef7b1e00d)

hope that helps

**Comment by mietzen** [comment] 2024-03-07 18:37
I build with the `--mono` flag if I understand the fira code repo right there are no ligatures when using the mono type. I’ll look at it on the weekend.

**Comment by mietzen** [comment] 2024-03-08 05:37
I build the font without the `--mono` flag:

[font.zip](https://github.com/mietzen/juliamono-nerd-font/files/14533645/font.zip) includes: 

```
JuliaMonoNerdFont-Bold.ttf
JuliaMonoNerdFont-Light.ttf
JuliaMonoNerdFont-Regular.ttf
```

Could you test if this fixes the issue? If so I'll update the release and from now on build with and without `--mono`.

Ok the Arrows work, but not the equal signs. That's confusing... 

Edit: But the behaviour is the same for the unpatched font

**Comment by mietzen** [comment] 2024-03-08 06:17
Ok as far as my understanding goes that is not a part that the NerdFontPatcher adds, the ligatures must be defined in the font itself. @tobsn and @cormullion please correct me if I'm wrong, otherwise I'll close this Issue.

Nevertheless it is always interesting to learn how unicode works 😉 

I also will add the non `--mono`, see #5

**Comment by mietzen** [comment] 2024-03-08 06:35
Ok I also found this repo: https://github.com/ToxicFrog/Ligaturizer

I'll try it later

**Comment by cormullion** [comment] 2024-03-08 10:03
Don't use the "-Latin" fonts - they're stripped down "Latin-only" versions designed for quick loading. 

|Font | Size|
|-----|-----:|
|JuliaMono-RegularLatin.ttf | 77108 |
|JuliaMono-Regular.ttf | 3147688 |

**Comment by cormullion** [comment] 2024-03-08 10:50
> fira code: ![ZuCcvKOzrNFWWl3U9eiySvFKvLnBx0fu](https://private-user-images.githubusercontent.com/109529/310974404-00696ea0-10c0-4269-acca-6e5348d4e95d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTQ4NzAsIm5iZiI6MTcwOTg5NDU3MCwicGF0aCI6Ii8xMDk1MjkvMzEwOTc0NDA0LTAwNjk2ZWEwLTEwYzAtNDI2OS1hY2NhLTZlNTM0OGQ0ZTk1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMDQyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzdkYTQ4ODk1ZDEzNzE0OTI5MjIzN2VhMDVjNzNkYWI3ZTE4NzJjM2RjOWNhMzI4ZmUwNjc4NzVmZmU4NDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aUJ2XpqGEoBEUaZlHIEkq4r07Of3unMxF1DETEkZyNU) ![fDoAvbGgxet4Y1beOpzgdun9CZtqmZMQ](https://private-user-images.githubusercontent.com/109529/310974408-7ae66a65-efc3-4614-84e3-6f0112354520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTQ4NzAsIm5iZiI6MTcwOTg5NDU3MCwicGF0aCI6Ii8xMDk1MjkvMzEwOTc0NDA4LTdhZTY2YTY1LWVmYzMtNDYxNC04NGUzLTZmMDExMjM1NDUyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMDQyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTdlMTM4N2JmOWJhNWNkZTI5ZDEzOGFhY2Q1ODQxZTkyNDI4OGM0MWYzMGJiODNkYzE5ZDJmNjkyM2ZkYjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rzI2mnNcNWOt2slyQr1ai6cUnotGjOYMyzP2agLMpQg)
> 
> JuliaMonoLatin Nerd Font Mono: ![eWw1Z6GE0MrEtfB4TIq1of1P5fsMLPlf](https://private-user-images.githubusercontent.com/109529/310974565-6ae82fb5-5ce0-4397-929f-1c9ef7b1e00d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTQ4NzAsIm5iZiI6MTcwOTg5NDU3MCwicGF0aCI6Ii8xMDk1MjkvMzEwOTc0NTY1LTZhZTgyZmI1LTVjZTAtNDM5Ny05MjlmLTFjOWVmN2IxZTAwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMDQyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjhhYmIyZDUzY2NjMTE1NjFhZGI1NDM5NjVhMGEyN2YxYjkwODBmNTA5MTJlMDBkZWUzMjU1M2VkZGIxNDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IUWV3KcrBAJhO_-_jE_5uUQOComyjSbAl12m-so1M-A)
> 
> hope that helps

But I think you'll be disappointed, since only these 'ligatures' are provided:

<img width="658" alt="Screenshot 2024-03-08 at 10 45 39" src="https://github.com/mietzen/juliamono-nerd-font/assets/52289/31831186-bb84-4ba1-bbe4-2c1da1c5e6ce">

If you want ligatures, Fira Code is definitely the font for you. I think hiding the gaps between the equals signs, or replacing glyphs with others that look like completely different Unicode characters is poor design... :)

**Comment by mietzen** [comment] 2024-03-08 10:52
> Ok I also found this repo: https://github.com/ToxicFrog/Ligaturizer
> 
> I'll try it later

![image](https://github.com/mietzen/juliamono-nerd-font/assets/31704359/dbf624f2-146c-491d-89b6-bdd5fccc7742)

I was able to build a font with working ligatures for the equal signs, but it's a pain in the ***. The Ligaturizer scripts is buggy and only works with:

- JuliaMono-Bold.ttf
- JuliaMono-BoldItalic.ttf
- JuliaMono-Regular.ttf
- JuliaMono-RegularItalic.ttf

all other files look like this:

`LigaJuliaMonoSemiBold-SemiBold.ttf` and the font name is `Liga JuliaMono Semibold Semibold`

There is a Issue in the repo, but without a fix: https://github.com/ToxicFrog/Ligaturizer/issues/53 

Also the script uses a old version (3.1) of fira code, updating to a newer version is not possible because fira code switched to `otf`. 

I will not integrate this into the workflows. But if you want to reproduce it, this is the script I used:

```
apt install python3-fontforge -y

git clone https://github.com/cormullion/juliamono

mkdir -p juliamono_ligaturized
mkdir -p juliamono-nerd-font/font/ligaturized/mono

git clone https://github.com/ToxicFrog/Ligaturizer --recurse-submodules

cd Ligaturizer

declare -a file_list=("JuliaMono-Bold.ttf" "JuliaMono-BoldItalic.ttf" "JuliaMono-Regular.ttf" "JuliaMono-RegularItalic.ttf")

for filename in "${file_list[@]}"; do
    echo $filename
    fontforge -lang py -script ligaturize.py ../juliamono/${filename} \
        --output-dir='../juliamono_ligaturized'
done

cd ..

docker run --rm -v `pwd`/juliamono_ligaturized:/in -v `pwd`/juliamono-nerd-font/font/ligaturized:/out nerdfonts/patcher --complete --careful
docker run --rm -v `pwd`/juliamono_ligaturized:/in -v `pwd`/juliamono-nerd-font/font/ligaturized/mono:/out nerdfonts/patcher --complete --careful --mono
```

From my point of view there ~~are two solutions~~ is one solution:

- Someone does a complete rewrite of  https://github.com/ToxicFrog/Ligaturizer, fixes the bugs and finds a way to use the `otf` fonts or there is a bug free and maintained alternative I overlooked, then I may consider integrating it
-  ~~@cormullion integrates the ligatures in JuliaMono~~

Edit: Missed @cormullion reply... down to one solution

**Closed as completed by mietzen** 2024-03-08 10:52 UTC

**Comment by mietzen** [comment] 2024-03-08 10:55
Forgot to upload the `.zip`:

[ligaturized.zip](https://github.com/mietzen/juliamono-nerd-font/files/14537225/ligaturized.zip)

But if you need updates or more / newer ligatures of fira you have to build them yourself or use `fira code`

**Comment by cormullion** [comment] 2024-03-08 11:04
Thanks for all your hard work @mietzen! 

I follow the issues on Fira Code' github repo. Ligatures are a continuing source of issues, problems, and additional work, and I don't regret my decision to not start down that path (even if I was funded 🤣).

**Comment by tobsn** [comment] 2024-03-11 18:12
@mietzen that works great yes!

You think you could rerun it again with Latin?
JuliaMonoLatin Nerd Font Mono

If not that's okay :)

**Comment by mietzen** [comment] 2024-03-11 18:17
@tobsn I already delete the files sorry, also I think the Ligaturizer script had some troubles with the latin font as well

**Comment by cormullion** [comment] 2024-03-11 19:04
> @mietzen that works great yes!
> 
> You think you could rerun it again with Latin? JuliaMonoLatin Nerd Font Mono

Out of interest, why do you want the Latin? You could always remove unwanted features with https://mutsuntsai.github.io/fontfreeze/ ...

**Comment by tobsn** [comment] 2024-03-11 19:34
![hLIRioG6DVeqdc7vaPw8b3VNifPepfA0](https://github.com/mietzen/juliamono-nerd-font/assets/109529/4b28d81a-78ac-4efe-9119-b33f250c3188)
![qAE4Jn8g36o9mKtJFOS90cfKs6bQv2AN](https://github.com/mietzen/juliamono-nerd-font/assets/109529/7dfe2fee-7174-4139-876e-65096c016d9b)

because Latin looks a lot better :)


Edit: Oh wait... Latin is the same as not Mono?

**Comment by cormullion** [comment] 2024-03-11 19:53
https://github.com/mietzen/juliamono-nerd-font/issues/3#issuecomment-1985402905
